name: ESLint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js with caching
      - name: Set up Node.js and cache dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '22.1.0'
          cache: 'npm'

      # Install dependencies with a clean environment
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Ensure Expo CLI is installed
      - name: Install Expo CLI
        run: npm install -g expo-cli

      # Run ESLint and fail the job if issues are found
      - name: Run ESLint
        run: npx eslint .
